print("I am Joy Beth Corral")
print("My spirit name is Dragon, ")
print("because I am born in the year 2000 and its strong")
print("When not in school", "I love to play guitar")
print("I dream of of being an engineer in the future")
